# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geosudreftoa.ui'
#
# Created: Wed Mar 12 10:20:38 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_geosudRefToa(object):
    def setupUi(self, geosudRefToa):
        geosudRefToa.setObjectName(_fromUtf8("geosudRefToa"))
        geosudRefToa.resize(500, 500)
        geosudRefToa.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        geosudRefToa.setFont(font)
        self.gridLayout_2 = QtGui.QGridLayout(geosudRefToa)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.teParam = QtGui.QTextEdit(geosudRefToa)
        self.teParam.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.teParam.setFont(font)
        self.teParam.setObjectName(_fromUtf8("teParam"))
        self.gridLayout_2.addWidget(self.teParam, 5, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbAbout = QtGui.QPushButton(geosudRefToa)
        self.pbAbout.setMinimumSize(QtCore.QSize(100, 0))
        self.pbAbout.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbAbout.setFont(font)
        self.pbAbout.setObjectName(_fromUtf8("pbAbout"))
        self.horizontalLayout.addWidget(self.pbAbout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(geosudRefToa)
        self.label.setMinimumSize(QtCore.QSize(80, 40))
        self.label.setMaximumSize(QtCore.QSize(80, 40))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("icon_geosud.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout_2.addLayout(self.horizontalLayout, 8, 2, 2, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gbInstrument = QtGui.QGroupBox(geosudRefToa)
        self.gbInstrument.setMinimumSize(QtCore.QSize(170, 150))
        self.gbInstrument.setMaximumSize(QtCore.QSize(170, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.gbInstrument.setFont(font)
        self.gbInstrument.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gbInstrument.setCheckable(False)
        self.gbInstrument.setObjectName(_fromUtf8("gbInstrument"))
        self.rbRapideye = QtGui.QRadioButton(self.gbInstrument)
        self.rbRapideye.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.rbRapideye.setObjectName(_fromUtf8("rbRapideye"))
        self.rbSpot = QtGui.QRadioButton(self.gbInstrument)
        self.rbSpot.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rbSpot.setObjectName(_fromUtf8("rbSpot"))
        self.rbLandsat = QtGui.QRadioButton(self.gbInstrument)
        self.rbLandsat.setGeometry(QtCore.QRect(10, 90, 82, 17))
        self.rbLandsat.setObjectName(_fromUtf8("rbLandsat"))
        self.gridLayout_4.addWidget(self.gbInstrument, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.pbLoadImg = QtGui.QPushButton(geosudRefToa)
        self.pbLoadImg.setMinimumSize(QtCore.QSize(60, 0))
        self.pbLoadImg.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbLoadImg.setFont(font)
        self.pbLoadImg.setObjectName(_fromUtf8("pbLoadImg"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pbLoadImg)
        self.leInput = QtGui.QLineEdit(geosudRefToa)
        self.leInput.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.leInput.setFont(font)
        self.leInput.setObjectName(_fromUtf8("leInput"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leInput)
        self.label_2 = QtGui.QLabel(geosudRefToa)
        self.label_2.setMinimumSize(QtCore.QSize(0, 23))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.pbMetadata = QtGui.QPushButton(geosudRefToa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbMetadata.sizePolicy().hasHeightForWidth())
        self.pbMetadata.setSizePolicy(sizePolicy)
        self.pbMetadata.setMinimumSize(QtCore.QSize(60, 0))
        self.pbMetadata.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbMetadata.setFont(font)
        self.pbMetadata.setObjectName(_fromUtf8("pbMetadata"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pbMetadata)
        self.leMetadata = QtGui.QLineEdit(geosudRefToa)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.leMetadata.setFont(font)
        self.leMetadata.setObjectName(_fromUtf8("leMetadata"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.leMetadata)
        self.pbLucky = QtGui.QPushButton(geosudRefToa)
        self.pbLucky.setMinimumSize(QtCore.QSize(60, 0))
        self.pbLucky.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbLucky.setFont(font)
        self.pbLucky.setObjectName(_fromUtf8("pbLucky"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.pbLucky)
        self.label_3 = QtGui.QLabel(geosudRefToa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 23))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.gridLayout_4.addLayout(self.formLayout, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 2, 2, 2, 1)
        self.glInfo = QtGui.QGridLayout()
        self.glInfo.setObjectName(_fromUtf8("glInfo"))
        self.gridLayout_2.addLayout(self.glInfo, 1, 2, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gpOutput = QtGui.QGroupBox(geosudRefToa)
        self.gpOutput.setMinimumSize(QtCore.QSize(170, 100))
        self.gpOutput.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.gpOutput.setFont(font)
        self.gpOutput.setObjectName(_fromUtf8("gpOutput"))
        self.rbRefNorm = QtGui.QRadioButton(self.gpOutput)
        self.rbRefNorm.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.rbRefNorm.setObjectName(_fromUtf8("rbRefNorm"))
        self.rbRefMilli = QtGui.QRadioButton(self.gpOutput)
        self.rbRefMilli.setGeometry(QtCore.QRect(10, 60, 141, 17))
        self.rbRefMilli.setObjectName(_fromUtf8("rbRefMilli"))
        self.gridLayout_5.addWidget(self.gpOutput, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbOutput = QtGui.QCheckBox(geosudRefToa)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.cbOutput.setFont(font)
        self.cbOutput.setObjectName(_fromUtf8("cbOutput"))
        self.gridLayout_3.addWidget(self.cbOutput, 3, 0, 1, 1)
        self.pbGetParam = QtGui.QPushButton(geosudRefToa)
        self.pbGetParam.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbGetParam.setFont(font)
        self.pbGetParam.setObjectName(_fromUtf8("pbGetParam"))
        self.gridLayout_3.addWidget(self.pbGetParam, 0, 0, 1, 1)
        self.pbConvert = QtGui.QPushButton(geosudRefToa)
        self.pbConvert.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbConvert.setFont(font)
        self.pbConvert.setObjectName(_fromUtf8("pbConvert"))
        self.gridLayout_3.addWidget(self.pbConvert, 5, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.pbOutput = QtGui.QPushButton(geosudRefToa)
        self.pbOutput.setMinimumSize(QtCore.QSize(40, 0))
        self.pbOutput.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.pbOutput.setFont(font)
        self.pbOutput.setObjectName(_fromUtf8("pbOutput"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.pbOutput)
        self.leOutput = QtGui.QLineEdit(geosudRefToa)
        self.leOutput.setObjectName(_fromUtf8("leOutput"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.leOutput)
        self.gridLayout_3.addLayout(self.formLayout_2, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 6, 2, 1, 1)

        self.retranslateUi(geosudRefToa)
        QtCore.QMetaObject.connectSlotsByName(geosudRefToa)
        geosudRefToa.setTabOrder(self.rbRapideye, self.rbSpot)
        geosudRefToa.setTabOrder(self.rbSpot, self.rbLandsat)
        geosudRefToa.setTabOrder(self.rbLandsat, self.pbLoadImg)
        geosudRefToa.setTabOrder(self.pbLoadImg, self.leInput)
        geosudRefToa.setTabOrder(self.leInput, self.pbMetadata)
        geosudRefToa.setTabOrder(self.pbMetadata, self.leMetadata)
        geosudRefToa.setTabOrder(self.leMetadata, self.pbLucky)
        geosudRefToa.setTabOrder(self.pbLucky, self.teParam)
        geosudRefToa.setTabOrder(self.teParam, self.pbGetParam)
        geosudRefToa.setTabOrder(self.pbGetParam, self.rbRefNorm)
        geosudRefToa.setTabOrder(self.rbRefNorm, self.rbRefMilli)
        geosudRefToa.setTabOrder(self.rbRefMilli, self.cbOutput)
        geosudRefToa.setTabOrder(self.cbOutput, self.pbOutput)
        geosudRefToa.setTabOrder(self.pbOutput, self.leOutput)
        geosudRefToa.setTabOrder(self.leOutput, self.pbConvert)
        geosudRefToa.setTabOrder(self.pbConvert, self.pbAbout)

    def retranslateUi(self, geosudRefToa):
        geosudRefToa.setWindowTitle(QtGui.QApplication.translate("geosudRefToa", "Geosud : TOA Reflectance", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAbout.setText(QtGui.QApplication.translate("geosudRefToa", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.gbInstrument.setTitle(QtGui.QApplication.translate("geosudRefToa", "Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRapideye.setText(QtGui.QApplication.translate("geosudRefToa", "RapidEye", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSpot.setText(QtGui.QApplication.translate("geosudRefToa", "Spot 5", None, QtGui.QApplication.UnicodeUTF8))
        self.rbLandsat.setText(QtGui.QApplication.translate("geosudRefToa", "Landsat 8", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLoadImg.setText(QtGui.QApplication.translate("geosudRefToa", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("geosudRefToa", "Load metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.pbMetadata.setText(QtGui.QApplication.translate("geosudRefToa", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLucky.setText(QtGui.QApplication.translate("geosudRefToa", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("geosudRefToa", "Load image(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.gpOutput.setTitle(QtGui.QApplication.translate("geosudRefToa", "Output format", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRefNorm.setText(QtGui.QApplication.translate("geosudRefToa", "reflectance (32 bits)", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRefMilli.setText(QtGui.QApplication.translate("geosudRefToa", "milli-reflectance (16 bits)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOutput.setText(QtGui.QApplication.translate("geosudRefToa", "output directory (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGetParam.setText(QtGui.QApplication.translate("geosudRefToa", "get TOA Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConvert.setText(QtGui.QApplication.translate("geosudRefToa", "convert DN to TOA", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOutput.setText(QtGui.QApplication.translate("geosudRefToa", "...", None, QtGui.QApplication.UnicodeUTF8))

